<%@ Page Language="C#" MasterPageFile="~/adminmaster.master" AutoEventWireup="true" CodeFile="adm_resume_display.aspx.cs" Inherits="adm_resume_display" Title="User Detail" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
<div>
        <asp:GridView ID="GridView1" DataSourceID="accessdb" AlternatingRowStyle-BackColor ="MediumTurquoise" runat="server"  BackColor="White" BorderColor="#CCCCCC" BorderStyle="None" 
         AllowPaging ="true"  PageSize ="15"
        BorderWidth="1px" CellPadding="3" DataKeyNames ="resumepath"    AutoGenerateColumns ="false" AutoGenerateDeleteButton ="true"   >
            <Columns>
           
             <asp:TemplateField  HeaderText ="Download" >
                   <ItemTemplate >
                       <asp:LinkButton Text ="Download"  ID ="linkbutton" runat ="server"  OnClick ="lnkdownload_click">
                   </asp:LinkButton>
                </ItemTemplate>
                </asp:TemplateField>
                 <asp:BoundField DataField ="uid" HeaderText ="Id"  SortExpression="id" ReadOnly="True"/>
                        <asp:BoundField DataField ="username" HeaderText ="User Name" HeaderStyle-Width ="150" />
                        <asp:BoundField DataField ="contact_no" HeaderText ="Contact No."  />
                        <asp:BoundField DataField ="email" HeaderText ="Email-Id" HeaderStyle-Width ="150" />
                        <asp:BoundField DataField ="applying_for" HeaderText ="Applying For" HeaderStyle-Width ="150" />
                        <asp:BoundField DataField ="address" HeaderText ="Address"  HeaderStyle-Width ="150"/>
                </Columns>
            <RowStyle ForeColor="#000066" />
            <FooterStyle BackColor="White" ForeColor="#000066" />
            <PagerStyle BackColor="White" ForeColor="#000066" HorizontalAlign="Left" />
            <SelectedRowStyle BackColor="#669999" Font-Bold="True" ForeColor="White" />
            <HeaderStyle BackColor="#006699" Font-Bold="True" ForeColor="White" />
            
            
        </asp:GridView>
        <asp:AccessDataSource runat ="server" DataFile ="~/App_Data/sednadb.mdb" ID ="accessdb"
         SelectCommand ="SELECT * FROM [tbcareer]"
         DeleteCommand ="DELETE FROM [tbcareer] WHERE [resumepath] = ?">
       </asp:AccessDataSource>
     </div>
</asp:Content>

